name: Build APK

"on": [push, workflow_dispatch]
jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up JDK 17
            uses: actions/setup-java@v4
            with:
              distribution: 'temurin'
              java-version: '17'

          - name: Setup Gradle
            uses: gradle/actions/setup-gradle@v3

          - name: Make gradlew executable
            run: chmod +x gradlew

          - name: Patch upstream bug
            run: |
              sed -i 's/if (supervisor.isRunning) supervisor.forceRestart()/\/\/ if (supervisor.isRunning) supervisor.forceRestart()/g'
              app/src/main/java/io/github/p1neapplexpress/openflux/service/SocksVpnService.kt

          - name: Build Debug APK
            run: ./gradlew assembleDebug

          - name: Upload APK Artifact
            uses: actions/upload-artifact@v4
            with:
              name: OpenFlux-NewCodec-APK
              path: app/build/outputs/apk/debug/app-debug.apk
